{"timestamp":"2025-10-07T13:26:21.191077Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-07T13:26:21.195541Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/mydag.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-07T13:26:21.399368Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.400889Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.401914Z","level":"info","event":"Current task name:accurate","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.402980Z","level":"info","event":"Dag name:my_dag","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.407262Z","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":78}
{"timestamp":"2025-10-07T13:26:21.415876Z","level":"info","event":"Running command: ['/usr/bin/bash', '-c', \"echo 'accurate\"]","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":88}
{"timestamp":"2025-10-07T13:26:21.468057Z","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":99}
{"timestamp":"2025-10-07T13:26:21.501148Z","level":"info","event":"/usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `''","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":106}
{"timestamp":"2025-10-07T13:26:21.502844Z","level":"info","event":"Command exited with return code 2","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook","filename":"subprocess.py","lineno":110}
{"timestamp":"2025-10-07T13:26:21.505924Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":972,"error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 2.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-07T13:26:21.509858Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.511122Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.512486Z","level":"info","event":"Task:<Task(BashOperator): accurate>","logger":"task.stdout"}
{"timestamp":"2025-10-07T13:26:21.513319Z","level":"info","event":"Failure caused by Bash command failed. The command returned a non-zero exit code 2.","logger":"task.stdout"}
